export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const CLEAR_FORM = "CLEAR_FORM";
export const HANDLE_FORM_CHANGE = "HANDLE_FORM_CHANGE";

export const TOGGLE_LOADING = "TOGGLE_LOADING";

export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";

export const GET_STATS_SUCCESS = "GET_STATS_SUCCESS";

export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

export const CREATE_QUIZ_SUCCESS = "CREATE_QUIZ_SUCCESS";

export const GET_QUIZZES_SUCCESS = "GET_QUIZZES_SUCCESS";

export const SET_EDIT_QUIZ = "SET_EDIT_QUIZ";

export const SET_QUIZ_ID = "SET_QUIZ_ID";

export const CHANGE_WRONG_ANSERS = "CHANGE_WRONG_ANSERS";

export const EDIT_QUIZ_SUCCESS = "EDIT_QUIZ_SUCCESS";

export const CREATE_QUESTION_SUCCESS = "CREATE_QUESTION_SUCCESS";

export const SET_EDIT_QUESTION = "SET_EDIT_QUESTION";

export const EDIT_QUESTION_SUCCESS = "EDIT_QUESTION_SUCCESS";

export const DELETE_QUESTION_SUCCESS = "DELETE_QUESTION_SUCCESS";

export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS";

export const GET_QUIZ_STUDENTS_SUCCESS = "GET_QUIZ_STUDENTS_SUCCESS";

export const CLEAR_FILTERS = " CLEAR_FILTERS";

export const CHANGE_PAGE = " CHANGE_PAGE";

export const LOGOUT_USER = "LOGOUT_USER";
